driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/metasploit-framework']

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: centos-5.11
    run_list: yum-epel::default
  - name: freebsd-10.1
    run_list: freebsd::portsnap
  - name: ubuntu-12.04
    run_list: apt::default

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/metasploit-framework
